version: '2'
services:
  website:
    build: ./website
  logstash:
    build: ./logstash
    volumes:
      - ./logstash/conf:/conf
      - ./logstash/patterns:/patterns
      - ./log:/log
  elasticsearch:
    image: elasticsearch:5.2
  kibana:
    image: kibana:5.2
    ports:
      - "127.0.0.1:5601:5601"
  nginx:
    image: nginx:1.11.9
    ports:
      - "127.0.0.1:8086:80"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
